### ISSUE TITLE
Bounded Async Channel is 100x worse than kanal sync channel when system is loaded

### ISSUE THREAD

**Issue by zstewar1** [fereidani/kanal#12]
I ran the benchmarks on a system where another process was using nearly 100% CPU on all cores while the benchmarks were running.

For the bounded channel with size 0 or 1, the performance of kanal-async (regardless of which lock implementation I used), ranged from ~15x worse to over 200x worse than the sync kanal implementation.

I'm not sure of the cause, and I'm filing this as a separate bug from #11  because it's not a complete hang (the benchmarks still completed), but it demonstrates there are substantial performance issues for kanal-async when on a loaded system.

![image](https://user-images.githubusercontent.com/5530349/196784333-742efc26-b6ad-4c49-8b8e-3bc9b8786efd.png)

**Comment by fereidani** [comment]
Thanks for your report, please send your OS and hardware too.
There is a UB in the async part that I'm working to solve. Currently, only the sync part passes the test in Miri.
Today I pushed a commit that fixes a race condition in async, if it's possible for you please repeat your test on the main branch again.

**Comment by zstewar1** [comment]
Async still seemed to have really bad running times even with the update (see below). It also still seemed to occasionally hang.

Code is now online in my forks: [kanal](https://github.com/zstewar1/kanal) (+branches `parkinglot` and `stdlock`) and [the benchmarks](https://github.com/zstewar1/rust-channel-benchmarks)

Note that my version of the run scrip sets the number of threads in the CPU consuming process to 400 because my system seems to have 96 cores * 2 CPUs * 2 threads per core, though I'm not totally sure what the system specs are because its a cloud machine that I use for work. If you try to reproduce these results, I recommend setting the number of threads to the total number of physical threads your machine supports, or a little bit higher, so with your Ryzen 2950X, try it with like 32-36 threads for the cpu loading program.

System is Linux 5.18.16, Debian based.
Rust 1.64.0

![image](https://user-images.githubusercontent.com/5530349/197268662-98af40b5-0ec0-4fed-8988-c0acdf5f6822.png)

**Comment by fereidani** [comment]
Thanks for your contribution to Kanal,
In the latest patches I temporary fixed Miri errors for async with an Arc to WakerStore, Also I can't reproduce the problem myself with the latest git version, My friend with apple m1 consistently has the same problem as yours with both flume-async and Kanal async, that makes me wonder if there is a possible problem in Tokio or not.
I need more time to investigate this issue.

**Comment by fereidani** [comment]
Could you please rerun your tests. the problem seems to be fixed.

**Comment by zstewar1** [comment]
Async now appears to be substantially faster than sync in the bounded-size channel tests.

![image](https://user-images.githubusercontent.com/5530349/197631493-5401e24a-0708-4ce5-83f9-a099d88635ae.png)

**Comment by fereidani** [comment]
Thank you for the time that you put in testing Kanal in last 5 days,
Yes in this update Kanal is utilizing full performance of Tokio context switching without using spin wait and heap allocation.
