### ISSUE TITLE
pointer bugs 2

### ISSUE THREAD

**Issue by beckend** [fereidani/kanal#19]
clone: https://github.com/beckend/kanal-bug
everything you need is in README.
this occurs when I do `sender.clone_sync()`;

**Comment by beckend** [comment]
you might as well write tests for `.clone_async()` to make sure it does not have the same bug.

**Comment by fereidani** [comment]
Thanks for the report! I really appreciate your contributions to Kanal with reporting these bugs. 
I don't think that's because of clone_sync.
I'm going to investigate this report and will let you know what was the problem.
Miri reports :
```
    |
224 |         self.ptr.as_ptr()
    |         ^^^^^^^^ using uninitialized data, but this operation requires initialized memory
    |
```

**Comment by fereidani** [comment]
Nice catch, there was a race condition in the read future, that actually lead to finding another race condition in send future too!
Both are patched with https://github.com/fereidani/kanal/commit/f615c8cd4702a46d03f4c29c0b1d07cfc38a7238 .
Could you please run your test with the following and check if the problem is solved?
```
[dependencies]
kanal = {git="https://github.com/fereidani/kanal"}
tokio = { version = "1", features = ["full"] }
anyhow = "*"
```

**Comment by beckend** [comment]
Nice! It works, closing, please do a release.

**Comment by fereidani** [comment]
Sure, will do that tomorrow, I need to rerun benchmarks and additional tests.
If it's possible for you for the next reports please use Tokio like this:
```
fn main() {
    let rt = tokio::runtime::Builder::new_current_thread()
        .enable_time()
        .build()
        .unwrap();
    rt.block_on(async_fn()).unwrap();
}
```
because it is easier to debug this one using Miri and other debug tools.

**Comment by beckend** [comment]
No problem
