### ISSUE TITLE
unsafe use of pointer to object on stack

### ISSUE THREAD

**Issue by qiujiangkun** [fereidani/kanal#3]
https://github.com/fereidani/kanal/blob/f3c2bf1b1db55b77598d30f633c0aac9eac00289/src/lib.rs#L191

Here `data` is taken pointer from, then forgotten. However, `data` is on stack, so it can be corrupted when being read again. Do you have justification for this?

In Golang this is safe, as Golang performs escape analysis, and any object taken references from and escapes are actually allocated to heap with GC. But in Rust it is not.

**Comment by qiujiangkun** [comment]
Ok, I read the code of the Receiver side. The Sender will not leave the function when the Receiver reads out the value. So data will remain valid then

**Comment by fereidani** [comment]
Yes, it's true, so it's not UB.
