### ISSUE TITLE
Intrusive variants

### ISSUE THREAD

**Issue by kabergstrom** [fereidani/kanal#30]
Thanks for making this library, the design is very cool.

I have a high performance scenario where I want to avoid heap allocations, and am happy to manage memory more manually.

Would it be possible to provide "intrusive" variants of the oneshot channels where the user provides heap memory to initialise, and have a callback for drop?

In my case, I have a mbuf-style implementation with a custom allocator, where the mbufs are reference counted, and it would be nice to be able to embed the kanal values into the mbuf header. I can treat kanal's OneshotInternal as a live reference to the mbuf itself, which would work nicely. It would enable me to acquire an IO request buffer with metadata + data + completion notification mechanism in one alloc.

**Comment by fereidani** [comment]
Hi, I'm glad you like it!
I thought about your problem, but unfortunately, the rust allocator API is unstable: https://doc.rust-lang.org/std/alloc/trait.Allocator.html .
every other implementation that I thought about had some unnecessary overhead on the default one-shot channel which most other users will use. as your use case is highly specific I recommend you write specific code for it too.
a suggestion that may help you is if you are spawning the thread or coroutine in the same place that you are constructing the buffer struct you can receive data from its handler just like a one-shot channel by returning the message inside the spawned code.
https://doc.rust-lang.org/std/thread/struct.JoinHandle.html#method.join

**Comment by kabergstrom** [comment]
Thanks for the swift reply, and for your consideration.

I'll think about a more specific messaging solution :)

**Comment by fereidani** [comment]
Anytime!
Goodluck
