### ISSUE TITLE
Incorrect Send and Sync bounds

### ISSUE THREAD

**Issue by raftario** [fereidani/kanal#33]
Currently both senders and receivers implement `Send` and `Sync` regardless of whether `T` implements `Send`, which is incorrect

**Comment by fereidani** [comment]
Thanks for reporting this, I pushed https://github.com/fereidani/kanal/commit/e55d07e34e728d6fab937d4efc73812cff96fd74
Please close the issue if you think the problem is fixed.

**Comment by raftario** [comment]
Yep the extra commits following that one seem to fix everything, thank you !
