### ISSUE TITLE
Unsound implementation of `as_sync`

### ISSUE THREAD

**Issue by shinmao** [fereidani/kanal#36]
Hi, I am the researcher from [sunlab](https://sunlab-gmu.github.io/). I am running our personal tools on open-source projects and found that these functions might be unsound.
### The source of unsoundness
https://github.com/fereidani/kanal/blob/2dc6a1ef0ad9a65bebb61ab993785142dd560a00/src/lib.rs#L994-L997
These functions are trying to transmute `AsyncSender` to `Sender`. 
```rs
#[cfg_attr(
    feature = "async",
    doc = r##"
)]
pub struct Sender<T> {
    internal: Internal<T>,
}

#[cfg(feature = "async")]
pub struct AsyncSender<T> {
    internal: Internal<T>,
}
```
Yes, just like the comments mentioned, the structures are totally same. However, the layout of `repr(Rust)` is not stable. It reserves the rights for compiler to insert paddings around the field for optimization. Only the totally same class could follow the same abi (e.g., `Sender` to `Sender`). The best way here is to annotate these `struct` as `repr(C)` to avoid UB.

All of `as_sync` functions might be affected: `AsyncReceiver::<T>::as_sync`, `Sender::<T>::as_async`, `AsyncSender::<T>::as_sync`, and `Receiver::<T>::as_async`.

**Comment by fereidani** [comment]
Hi, Thank you for finding this. Would you please send a PR for it?

**Comment by shinmao** [comment]
I just created a [PR](https://github.com/fereidani/kanal/pull/37), please check:)

**Comment by fereidani** [comment]
Merged, Thank you for your contribution!
