### ISSUE TITLE
mixing sync and async context

### ISSUE THREAD

**Issue by grantweii** [fereidani/kanal#42]
I saw the following comment in the AsyncSender impl 

> // JUST FOR EXAMPLE IT IS WRONG TO USE SYNC INSTANCE IN ASYNC CONTEXT

why is this the case?

**Comment by MiniaczQ** [comment]
This isn't anything `kanal` specific, when working in async contexts you shouldn't use blocking functions, because they lock up an entire async executor thread, async primitives will yield to the executor without blocking it entirely.

**Comment by grantweii** [comment]
that makes sense, thanks
