### ISSUE TITLE
API design for oneshot sender

### ISSUE THREAD

**Issue by JakkuSakura** [fereidani/kanal#46]
OneshotAsyncSender::send is async, and OneshotSender::send uses a for loop
they are not necessary, as an oneshot sender can immediately know if a receiver is dropped.

e.g. tokio::sync::oneshot::Sender provides a send that immediately returns

**Comment by fereidani** [comment]
The sender relies on the receiver to allocate a buffer on its stack, other libraries use heap memory for transfer, kanal uses the stack. Loop is there that in case of contention algorithm could adapt to the changes in transfer protocol.
