### ISSUE TITLE
Oneshot: UB triggered when using Axum

### ISSUE THREAD

**Issue by nastynaz** [fereidani/kanal#47]
I used the `AsyncSender` and `AsyncReceiver` channels and this code started panicking when using kanal. I tried it with Flume and Tokio mpsc channels and there's no issue.

It happens when a client cancels their HTTP request, causing Axum to cancel the future that calls this:
```rust
  pub async fn pnl_report(&self) -> HashMap<Coin, CurrentPnl> {
      let (tx, rx) = tokio::sync::oneshot::channel();
      self.query_sender // <-- kanal async sender
          .send(PNLQuery::Report(tx))
          .await
          .expect("BUG: query sender channel should never be closed");

      rx.await
          .expect("BUG: oneshot query sender should never be closed") // <- this panics
  }
```
It appears that somehow the `.send()` is getting cancelled but the `rx.await` isn't.

**Comment by fereidani** [comment]
I'm dropping oneshot feature, going to continue it in another package. Its design need to change and it is not compatible with mpmc channel signal design.

**Comment by fereidani** [comment]
there are already report open for this bug.

**Comment by SaltyKitkat** [comment]
> I'm dropping oneshot feature, going to continue it in another package. Its design need to change and it is not compatible with mpmc channel signal design.

Hi! Thank you for your great work bringing us kanal. And I'm looking forward to your version of oneshot channel. I've explored your public repos, but didn't find it and wondering where can I get it :)
