### ISSUE TITLE
receiver hangs forever

### ISSUE THREAD

**Issue by veber-alex** [fereidani/kanal#8]
https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=8c4019721056c7bf7ccfef8f6f4a6d86

This code hangs forever but finishes with std mpsc or crossbeam.
Removing the sleep fixes the issue.

**Comment by fereidani** [comment]
Thank you, I'm investigating it.

**Comment by fereidani** [comment]
There is a race condition that happens sometimes in release builds and not development builds.

**Comment by fereidani** [comment]
The bug is fixed in the GitHub version, could you please retest and report if you can reproduce the bug or not?

**Comment by fereidani** [comment]
Feel free to reopen the issue if you been able to reproduce the problem,
Thank you for your report
